### ISSUE TITLE
Error: 'Activation' object has no attribute 'paths'

### ISSUE THREAD

**Issue by zizhaowillwang** [nnn911/ScoreBasedDenoising#3]
Hi Daniel,

I encountered this error when running "RuntimeError: Export of frame 0 failed, because data pipeline evaluation has failed. 'Activation' object has no attribute 'paths'".

I did manage to run it on my MacBook, but the error comes when I run it on cluster. I maintained versions ovito=3.10.5, torch=2.2.2, torch-geometric == 2.5.3. Also they have the same python, numpy, sklearn versions. 

Could you guide me how to debug on this? Thanks in advance.

Here is my code. 
from ovito.io import *
from ovito.modifiers import *
from ovito.data import *
from ovito.pipeline import *
from scoreBasedDenoising import *

pipeline = import_file('test1.gsd')

pipeline.modifiers.append(ScoreBasedDenoising(
   steps = 1,
   structure = 'FCC'))

export_file(pipeline, 'test1_fl3.xyz', "xyz",
       columns = ["Position.X", "Position.Y", "Position.Z"],precision = 3)

**Comment by nnn911** [comment]
Thank you very much for your report. It was related to the version of e3nn. Should be fixed now.
